inherit_from: .rubocop_todo.yml

# Turn on RSpec cops
require: rubocop-rspec
AllCops:
  DisplayCopNames: true
  Include:
    - Rakefile
  Exclude:
    - Gemfile.lock
    - '**/*.md'

Bundler/OrderedGems:
  Exclude:
    - Gemfile

# --- Layout ---

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

# --- Lint ---

# --- Metrics ---

Metrics/LineLength:
  Max: 120 #  this isn't 1994
  Exclude:
    - spec/lyber_utils/file_utilities_spec.rb

# --- Naming ---

Naming/FileName:
  Exclude:
    - Gemfile
    - lyber-utils.gemspec
    - lib/lyber-utils.rb

# --- Performance ---

# --- RSpec ---

# --- Style ---

Style/StringLiterals:
  Enabled: false # ' vs " isn't a big deal for readability or maintainability or execution time

Style/SymbolArray:
  Exclude:
    - Rakefile # [:spec, :rubocop] isn't a big deal
