notifications:
  email: false

rvm:
  - 2.5.3
  - 2.4.5
  - 2.3.1
  - 2.2.4
  - 2.1.8

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
language: ruby

script:
  - bundle exec rake
